const actions = {
  FETCH_PRODUCTS_REQUESTED: 'FETCH_PRODUCTS_REQUESTED',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  ITEM_ADDED_TO_CART: 'ITEM_ADDED_TO_CART',
  ITEM_REMOVED_FROM_CART: 'ITEM_REMOVED_FROM_CART',
  CART_ITEM_COUNT_CHANGED: 'CART_ITEM_COUNT_CHANGED'
}

export default actions;