const actions = {
  FETCH_PRODUCTS_REQUESTED: 'FETCH_PRODUCTS_REQUESTED',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  ITEM_ADDED_TO_CART: 'ITEM_ADDED_TO_CART'
}

export default actions;