const actions = {
  FETCH_PRODUCTS_REQUESTED: 'FETCH_PRODUCTS_REQUESTED',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  
  ITEM_ADDED_TO_CART: 'ITEM_ADDED_TO_CART',
  ITEM_REMOVED_FROM_CART: 'ITEM_REMOVED_FROM_CART',
  ALL_ITEMS_REMOVED_FROM_CART: 'ALL_ITEMS_REMOVED_FROM_CART',
  
  MENU_TOGGLED: 'MENU_TOGGLED'
}

export default actions;